# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('school_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='phone_number', max_length=50, null=True)),
                ('career', models.TextField(blank=True, null=True)),
                ('mentor_bool', models.BooleanField(default=False)),
                ('github', models.URLField(blank=True, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='_user_followers_+', to='users_api.User')),
                ('following', models.ManyToManyField(blank=True, related_name='_user_following_+', to='users_api.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
